# The register of sanctioned and carried over-ceiling units, read as data. A unit over a
# ceiling passes the gate only when this file records a figure it does not exceed, so the
# lookup has to resolve the register from this unit's own location rather than from the
# caller's working directory.

include_guard(GLOBAL)

get_filename_component(size_register_file "${CMAKE_CURRENT_LIST_DIR}/../../EXCEPTIONS.md" REALPATH)

if(NOT EXISTS "${size_register_file}")
    message(FATAL_ERROR "size register missing: ${size_register_file}")
endif()

function(size_register_cells row out)
    set(${out} "" PARENT_SCOPE)
    string(STRIP "${row}" row)
    if(NOT row MATCHES "^\\|.*\\|$")
        return()
    endif()
    string(REGEX REPLACE "^\\||\\|$" "" row "${row}")
    string(REPLACE "|" ";" cells "${row}")
    set(stripped "")
    foreach(cell IN LISTS cells)
        string(STRIP "${cell}" cell)
        list(APPEND stripped "${cell}")
    endforeach()
    set(${out} "${stripped}" PARENT_SCOPE)
endfunction()

function(size_register_path cell out)
    set(${out} "" PARENT_SCOPE)
    if(NOT cell MATCHES "^`(.+)`$")
        return()
    endif()
    set(path "${CMAKE_MATCH_1}")
    if(NOT path MATCHES "/")
        return()
    endif()
    get_filename_component(name "${path}" NAME)
    if(path MATCHES "\\.(h|hpp|cpp|cc|cmake)$" OR name STREQUAL "CMakeLists.txt")
        set(${out} "${path}" PARENT_SCOPE)
    endif()
endfunction()

# A row is a measurement because of its shape, never because of the section it sits in:
# the first cell must be a backtick-quoted path and the figures must be bare integers.
# Section walking would break the moment a table is added, reordered or retitled, and a
# looser shape test would let a prose row with two numbers in it fabricate a ceiling.
# A three-cell row records a count and a longest span; the gate is held to the span.
function(size_register_entry row out_metric out_entry)
    set(${out_metric} "" PARENT_SCOPE)
    size_register_cells("${row}" cells)
    list(LENGTH cells count)
    if(count LESS 2 OR count GREATER 3)
        return()
    endif()
    list(GET cells 0 first)
    list(GET cells 1 second)
    size_register_path("${first}" path)
    if(path STREQUAL "" OR NOT second MATCHES "^[0-9]+$")
        return()
    endif()
    if(count EQUAL 2)
        set(${out_metric} lines PARENT_SCOPE)
        set(${out_entry} "${path}=${second}" PARENT_SCOPE)
        return()
    endif()
    list(GET cells 2 third)
    if(third MATCHES "^[0-9]+$")
        set(${out_metric} functions PARENT_SCOPE)
        set(${out_entry} "${path}=${third}" PARENT_SCOPE)
    endif()
endfunction()

function(read_size_register)
    file(STRINGS "${size_register_file}" rows)
    set(lines "")
    set(functions "")
    foreach(row IN LISTS rows)
        size_register_entry("${row}" metric entry)
        if(metric STREQUAL "lines")
            list(APPEND lines "${entry}")
        elseif(metric STREQUAL "functions")
            list(APPEND functions "${entry}")
        endif()
    endforeach()
    set(size_register_lines "${lines}" PARENT_SCOPE)
    set(size_register_functions "${functions}" PARENT_SCOPE)
endfunction()

function(registered_figure list_name path out)
    set(${out} none PARENT_SCOPE)
    foreach(entry IN LISTS ${list_name})
        string(REGEX REPLACE "=[0-9]+$" "" entry_path "${entry}")
        if(entry_path STREQUAL path)
            string(REGEX REPLACE "^.*=" "" figure "${entry}")
            set(${out} "${figure}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
endfunction()
