#ifndef HPP_GUARD_NUCLEUS_COMPLETION_BASH_EMITTER_H
#define HPP_GUARD_NUCLEUS_COMPLETION_BASH_EMITTER_H

#include "nucleus/completion/shell_emitter.h"
#include "nucleus/completion/completion_model.h"

#include <string>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace nucleus {

// The bash emitter. It renders a `complete -F` function bound to the program. All
// of bash's sharp edges are confined here:
//
//   * COMP_WORDBREAKS. By default bash treats `=`, `:` and `@` as word breaks, so
//     when the user types `--flag=<TAB>` the current word `$cur` is just the part
//     after `=`. We lean INTO that rather than fighting it: a `case "$cur" in`
//     arm is impossible to match against the whole `--flag=value` (it is already
//     split), so the function instead inspects the PREVIOUS resjoin. The robust,
//     portable idiom used here reconstructs the flag from `${COMP_WORDS[@]}` and
//     matches `--flag=*`, then completes only the value tail `${cur#*=}`. This
//     split-after-`=` is precisely what sidesteps the `=` word-break by
//     construction -- no `compopt` gymnastics needed.
//   * The `:` word-break (e.g. a value containing a colon) is healed by a guarded
//     `__ltrim_colon_completions`, which is present in bash-completion but may be
//     absent; the call is guarded so the script degrades cleanly without it.
//   * Quoting. Single-quoting the word list holds it to one literal in the parse of
//     the SCRIPT, which is not the parse that matters: `compgen -W` EXPANDS every
//     word it produces -- brace, tilde, parameter and arithmetic expansion, command
//     substitution and process substitution all run at that second, runtime stage.
//     Each flag and value is therefore escaped for that stage here at the emitter,
//     never on the word of a validator upstream, and escaped against an ALLOWLIST so
//     that no construct anyone has to think of first survives into it.
//   * The field separator, and pathname expansion. `compgen -W` splits its word list
//     on IFS, and the unquoted command substitution that fills COMPREPLY splits again
//     on the same characters -- so a value carrying a separator has to survive both.
//     Each value backslash-escapes its own separators for the first split, and the
//     assignment narrows IFS to a newline for the second while restoring the default
//     inside the substitution, where compgen still needs it. That same unquoted
//     substitution also GLOBS what it produces, which nothing escaped at the emitter
//     can reach because compgen has already consumed the backslash -- so the
//     assignment runs with globbing suppressed and puts the caller's setting back.
//
// None of this leaks back into the generator or the model.
class bash_emitter final : public shell_emitter
{
public:
    std::string emit(const completion_model &model) const override
    {
        const std::string fn = "_" + sanitize_ident(model.prog) + "_complete";
        std::string const all_flags = join_flags(model.options);

        std::string out;
        out += "# bash completion for " + model.prog + "\n";
        out += "# Generated by nucleus -- do not edit by hand.\n";
        out += fn + "()\n{\n";
        out += "    local cur prev words cword\n";
        out += "    COMPREPLY=()\n";
        out += "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n";
        out += "    local flags=" + single_quote(all_flags) + "\n";
        out += "\n";
        // Value completion. When the user types `--flag=<TAB>`, bash's default
        // COMP_WORDBREAKS keeps `=` as part of $cur only if `=` is removed from
        // the break set; to stay portable we instead reconstruct the whole word
        // from the words array so the `--flag=value` form is visible, then split
        // on `=` ourselves and complete only the value tail. This split-after-`=`
        // sidesteps the `=` word-break by construction.
        out += "    local whole=\"$cur\"\n";
        out += "    if [[ \"${COMP_WORDS[COMP_CWORD-1]}\" == \"=\" ]]; then\n";
        out += "        whole=\"${COMP_WORDS[COMP_CWORD-2]}=${cur}\"\n";
        out += "    fi\n";
        out += "    if [[ \"$whole\" == --*=* ]]; then\n";
        out += "        local cur=\"$whole\"\n";
        out += "        local flag=\"${cur%%=*}\"\n";
        out += "        local val=\"${cur#*=}\"\n";
        out += "        case \"$flag\" in\n";
        for(const completion_option &opt : model.options)
        {
            if(opt.values.empty())
                continue;
            out += "        " + single_quote(opt.flag) + ")\n";
            out += reply_assignment("            ", single_quote(join_values(opt.values)), "$val");
            out += "            __ltrim_colon_completions \"$cur\" 2>/dev/null\n";
            out += "            return 0\n";
            out += "            ;;\n";
        }
        out += "        esac\n";
        out += "        return 0\n";
        out += "    fi\n";
        out += "\n";
        // Flag-name completion.
        out += reply_assignment("    ", "\"$flags\"", "$cur");
        out += "    __ltrim_colon_completions \"$cur\" 2>/dev/null\n";
        out += "    return 0\n";
        out += "}\n";
        out += "complete -F " + fn + " " + model.prog + "\n";
        return out;
    }

private:
    // The one place globbing is suppressed and restored. `case $-` reads the caller's setting
    // portably, where `local -` would need bash 4.4 -- above the floor this script supports.
    static std::string reply_assignment(const std::string &pad, const std::string &words,
                                        const std::string &current)
    {
        return pad + "local noglob=0; case $- in *f*) noglob=1 ;; esac; set -f\n"
             + pad + R"(local IFS=$'\n'; COMPREPLY=( $(IFS=$' \t\n'; compgen -W )"
             + words + " -- \"" + current + "\") )\n"
             + pad + "if [ \"$noglob\" = 0 ]; then set +f; fi\n";
    }

    // bash single-quote escaping: close the quote, emit an escaped quote, reopen.
    static std::string single_quote(const std::string &text)
    {
        std::string out = "'";
        for(char const c : text)
        {
            if(c == '\'')
                out += "'\\''";
            else
                out.push_back(c);
        }
        out.push_back('\'');
        return out;
    }

    // A safe shell identifier for the function name (non-alnum -> '_').
    static std::string sanitize_ident(const std::string &text)
    {
        std::string out;
        out.reserve(text.size());
        for(char const c : text)
        {
            const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                         || (c >= '0' && c <= '9') || c == '_';
            out.push_back(ok ? c : '_');
        }
        return out;
    }

    static std::string join_flags(
        const std::vector<completion_option> &options)
    {
        std::string out;
        for(std::size_t i = 0; i < options.size(); ++i)
        {
            if(i != 0)
                out.push_back(' ');
            out += word(options[i].flag);
        }
        return out;
    }

    // Enumerating what a shell does to a word is a guess, and a word list is a code
    // channel, so the test runs the other way: a byte survives unescaped only by being in
    // the safe set, and every other byte -- control bytes and everything at or above 0x7f
    // included -- is backslashed. A backslashed byte is exempt from every expansion
    // `compgen -W` performs and its backslash is dropped by quote removal, so a multi-byte
    // sequence escaped byte by byte reads back identical. `*` is safe because `compgen -W`
    // does no pathname expansion: escaping it is consumed with no effect on the candidate,
    // and the ordinal wildcard stays readable in the emitted script. A newline is the one
    // byte this encoding cannot carry, since a backslash before it is a line continuation.
    static std::string word(const std::string &text)
    {
        static constexpr std::string_view safe_punctuation = "-_./=+,:@%*";
        std::string out;
        for(char const c : text)
        {
            const bool safe = static_cast<std::uint8_t>(c) < 0x7f
                           && ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                               || (c >= '0' && c <= '9')
                               || safe_punctuation.find(c) != std::string_view::npos);
            if(!safe)
                out.push_back('\\');
            out.push_back(c);
        }
        return out;
    }

    static std::string join_values(
        const std::vector<std::string> &values)
    {
        std::string out;
        for(std::size_t i = 0; i < values.size(); ++i)
        {
            if(i != 0)
                out.push_back(' ');
            out += word(values[i]);
        }
        return out;
    }
};

}

#endif
