#ifndef HPP_GUARD_NUCLEUS_COMPLETION_ZSH_EMITTER_H
#define HPP_GUARD_NUCLEUS_COMPLETION_ZSH_EMITTER_H

#include "nucleus/completion/shell_emitter.h"
#include "nucleus/completion/completion_model.h"

#include <string>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace nucleus {

// The zsh emitter. zsh has its OWN completion grammar -- it is deliberately not a
// re-quoted bash script. The output is a `#compdef`-tagged function that calls
// `_arguments -s`, one spec per flag:
//
//     '--logging-level=[set the logging level]:level:(debug info warn error)'
//
// zsh parses `--flag=` natively and drives the value menu from the `(...)` group,
// so there is no COMP_WORDBREAKS handling here at all -- that whole class of bash
// edge case simply does not exist in this dialect. The flags WITHOUT a value set
// emit a bare `'--flag[desc]'` spec. All zsh-spec quoting (escaping `:`, `[`, `]`,
// `(`, `)` and the single-quote that wraps each spec) is confined to this file.
class zsh_emitter final : public shell_emitter
{
public:
    std::string emit(const completion_model &model) const override
    {
        std::string out;
        out += "#compdef " + model.prog + "\n";
        out += "# zsh completion for " + model.prog + "\n";
        out += "# Generated by nucleus -- do not edit by hand.\n";
        out += "_" + sanitize_ident(model.prog) + "()\n{\n";
        out += "    _arguments -s \\\n";
        for(std::size_t i = 0; i < model.options.size(); ++i)
        {
            const completion_option &opt = model.options[i];
            const bool last = (i + 1 == model.options.size());
            out += "        " + single_quote(spec_for(opt));
            out += last ? "\n" : " \\\n";
        }
        out += "}\n";
        out += "_" + sanitize_ident(model.prog) + " \"$@\"\n";
        return out;
    }

private:
    // One `_arguments` spec for an option. With values it carries the `=` form and
    // a `(...)` value group; without, it is a bare presence flag.
    static std::string spec_for(const completion_option &opt)
    {
        const std::string flag = word(opt.flag);
        const std::string desc = brackets(opt.description);
        if(opt.values.empty())
            return flag + "[" + desc + "]";

        std::string group;
        for(std::size_t i = 0; i < opt.values.size(); ++i)
        {
            if(i != 0)
                group.push_back(' ');
            group += word(opt.values[i]);
        }
        return flag + "=[" + desc + "]:value:(" + group + ")";
    }

    // A description is prose, so the word list's byte allowlist cannot be reused here -- it would
    // backslash every space. `\ [ ] :` are what an `_arguments` spec reads as structure around a
    // description, and an unescaped `]` is the only route out of one and into the spec's action,
    // which is the field `_arguments` evaluates; everything else is inert because the whole spec
    // is a single-quoted word. A non-printable byte is substituted with its caret rendering rather
    // than passed through or dropped, so a newline cannot break the spec across the script's lines
    // and an escape sequence cannot reach the terminal that draws the menu.
    static std::string brackets(const std::string &text)
    {
        std::string out;
        for(char const c : text)
        {
            const auto byte = static_cast<std::uint8_t>(c);
            if(byte < 0x20 || byte == 0x7f)
            {
                out.push_back('^');
                append_escaped(out, static_cast<char>(byte ^ 0x40));
            }
            else
                append_escaped(out, c);
        }
        return out;
    }

    static void append_escaped(std::string &out, char c)
    {
        static constexpr std::string_view structural = "\\[]:";
        if(structural.find(c) != std::string_view::npos)
            out.push_back('\\');
        out.push_back(c);
    }

    // Every string the spec carries as a WORD -- a flag at its head, a member of a
    // `(...)` value group -- is escaped here against an allowlist rather than a list of
    // dangerous characters: a byte survives unescaped only by being in the safe set, and
    // every other byte is backslashed. That covers the spec-grammar delimiters, the
    // whitespace separating members, and the expansions zsh runs over a word once it reads
    // it back out of the spec, without any of them having been thought of first. The safe
    // set is the bash emitter's without `:`, which separates the fields of an `_arguments`
    // spec. The escape is unconditional; what a registration rule refuses is not this
    // file's business, and assuming otherwise is what left the word list a code channel.
    static std::string word(const std::string &text)
    {
        static constexpr std::string_view safe_punctuation = "-_./=+,@%*";
        std::string out;
        for(char const c : text)
        {
            const bool safe = static_cast<std::uint8_t>(c) < 0x7f
                           && ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                               || (c >= '0' && c <= '9')
                               || safe_punctuation.find(c) != std::string_view::npos);
            if(!safe)
                out.push_back('\\');
            out.push_back(c);
        }
        return out;
    }

    // zsh single-quote escaping: a single quote cannot appear inside '...', so we
    // close, emit an escaped quote, and reopen -- the same idiom every POSIX shell
    // accepts.
    static std::string single_quote(const std::string &text)
    {
        std::string out = "'";
        for(char const c : text)
        {
            if(c == '\'')
                out += "'\\''";
            else
                out.push_back(c);
        }
        out.push_back('\'');
        return out;
    }

    static std::string sanitize_ident(const std::string &text)
    {
        std::string out;
        out.reserve(text.size());
        for(char const c : text)
        {
            const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                         || (c >= '0' && c <= '9') || c == '_';
            out.push_back(ok ? c : '_');
        }
        return out;
    }
};

}

#endif
