#ifndef HPP_GUARD_NUCLEUS_COMPLETION_ZSH_EMITTER_H
#define HPP_GUARD_NUCLEUS_COMPLETION_ZSH_EMITTER_H

#include "nucleus/completion/shell_emitter.h"
#include "nucleus/completion/completion_model.h"

#include <string>
#include <vector>
#include <cstddef>

namespace nucleus {

// The zsh emitter. zsh has its OWN completion grammar -- it is deliberately not a
// re-quoted bash script. The output is a `#compdef`-tagged function that calls
// `_arguments -s`, one spec per flag:
//
//     '--logging-level=[set the logging level]:level:(debug info warn error)'
//
// zsh parses `--flag=` natively and drives the value menu from the `(...)` group,
// so there is no COMP_WORDBREAKS handling here at all -- that whole class of bash
// edge case simply does not exist in this dialect. The flags WITHOUT a value set
// emit a bare `'--flag[desc]'` spec. All zsh-spec quoting (escaping `:`, `[`, `]`,
// `(`, `)` and the single-quote that wraps each spec) is confined to this file.
class zsh_emitter final : public shell_emitter
{
public:
    std::string emit(const completion_model &model) const override
    {
        std::string out;
        out += "#compdef " + model.prog + "\n";
        out += "# zsh completion for " + model.prog + "\n";
        out += "# Generated by nucleus -- do not edit by hand.\n";
        out += "_" + sanitize_ident(model.prog) + "()\n{\n";
        out += "    _arguments -s \\\n";
        for(std::size_t i = 0; i < model.options.size(); ++i)
        {
            const completion_option &opt = model.options[i];
            const bool last = (i + 1 == model.options.size());
            out += "        " + single_quote(spec_for(opt));
            out += last ? "\n" : " \\\n";
        }
        out += "}\n";
        out += "_" + sanitize_ident(model.prog) + " \"$@\"\n";
        return out;
    }

private:
    // One `_arguments` spec for an option. With values it carries the `=` form and
    // a `(...)` value group; without, it is a bare presence flag.
    static std::string spec_for(const completion_option &opt)
    {
        const std::string desc = brackets(opt.description);
        if(opt.values.empty())
            return opt.flag + "[" + desc + "]";

        std::string group;
        for(std::size_t i = 0; i < opt.values.size(); ++i)
        {
            if(i != 0)
                group.push_back(' ');
            group += paren(opt.values[i]);
        }
        return opt.flag + "=[" + desc + "]:value:(" + group + ")";
    }

    // Backslash-escape the characters that terminate a `[...]` description.
    static std::string brackets(const std::string &text)
    {
        std::string out;
        for(char const c : text)
        {
            if(c == '[' || c == ']' || c == ':')
                out.push_back('\\');
            out.push_back(c);
        }
        return out;
    }

    // Backslash-escape the characters that have meaning inside a `(...)` value
    // group: the group delimiters and the whitespace that separates members.
    static std::string paren(const std::string &text)
    {
        std::string out;
        for(char const c : text)
        {
            if(c == '(' || c == ')' || c == ' ' || c == ':')
                out.push_back('\\');
            out.push_back(c);
        }
        return out;
    }

    // zsh single-quote escaping: a single quote cannot appear inside '...', so we
    // close, emit an escaped quote, and reopen -- the same idiom every POSIX shell
    // accepts.
    static std::string single_quote(const std::string &text)
    {
        std::string out = "'";
        for(char const c : text)
        {
            if(c == '\'')
                out += "'\\''";
            else
                out.push_back(c);
        }
        out.push_back('\'');
        return out;
    }

    static std::string sanitize_ident(const std::string &text)
    {
        std::string out;
        out.reserve(text.size());
        for(char const c : text)
        {
            const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                         || (c >= '0' && c <= '9') || c == '_';
            out.push_back(ok ? c : '_');
        }
        return out;
    }
};

}

#endif
