#include "nucleus/completion/completion_generator.h"

#include "nucleus/schema/anchor.h"
#include "nucleus/schema/schema.h"
#include "nucleus/schema/schema_registry.h"

#include "nucleus/keyspace/key_path.h"

#include <catch2/catch_test_macros.hpp>

#include <string>

using nucleus::shell;
using nucleus::anchor;
using nucleus::key_path;
using nucleus::schema_registry;
using nucleus::generate_completion;

namespace {

key_path path_of(const char *text) { return key_path::parse(text).value(); }

// The fixture schema the golden scripts below are pinned to: a value-constrained
// enum element, a plain root element, and a nested plain element. surface() is
// deterministically ordered, so the projection is reproducible byte-for-byte.
schema_registry fixture()
{
    schema_registry reg;
    REQUIRE(reg.attach(nucleus::element("logging", anchor::root())));
    REQUIRE(reg.attach(nucleus::enum_element("level", anchor::keyspace(path_of("logging")),
                                     {"debug", "info", "warn", "error"})));
    REQUIRE(reg.attach(nucleus::element("plexus", anchor::root())));
    REQUIRE(reg.attach(nucleus::element("port", anchor::keyspace(path_of("plexus")))));
    return reg;
}

// The pinned bash script for the fixture. A drift here is intentional and must be
// reviewed -- it means the projection or the bash emitter changed.
const std::string expected_bash =
    "# bash completion for myapp\n"
    "# Generated by nucleus -- do not edit by hand.\n"
    "_myapp_complete()\n"
    "{\n"
    "    local cur prev words cword\n"
    "    COMPREPLY=()\n"
    "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
    "    local flags='--logging --logging-level --plexus --plexus-port'\n"
    "\n"
    "    local whole=\"$cur\"\n"
    "    if [[ \"${COMP_WORDS[COMP_CWORD-1]}\" == \"=\" ]]; then\n"
    "        whole=\"${COMP_WORDS[COMP_CWORD-2]}=${cur}\"\n"
    "    fi\n"
    "    if [[ \"$whole\" == --*=* ]]; then\n"
    "        local cur=\"$whole\"\n"
    "        local flag=\"${cur%%=*}\"\n"
    "        local val=\"${cur#*=}\"\n"
    "        case \"$flag\" in\n"
    "        '--logging-level')\n"
    "            COMPREPLY=( $(compgen -W 'debug info warn error' -- \"$val\") )\n"
    "            __ltrim_colon_completions \"$cur\" 2>/dev/null\n"
    "            return 0\n"
    "            ;;\n"
    "        esac\n"
    "        return 0\n"
    "    fi\n"
    "\n"
    "    COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n"
    "    __ltrim_colon_completions \"$cur\" 2>/dev/null\n"
    "    return 0\n"
    "}\n"
    "complete -F _myapp_complete myapp\n";

const std::string expected_zsh =
    "#compdef myapp\n"
    "# zsh completion for myapp\n"
    "# Generated by nucleus -- do not edit by hand.\n"
    "_myapp()\n"
    "{\n"
    "    _arguments -s \\\n"
    "        '--logging[]' \\\n"
    "        '--logging-level=[]:value:(debug info warn error)' \\\n"
    "        '--plexus[]' \\\n"
    "        '--plexus-port[]'\n"
    "}\n"
    "_myapp \"$@\"\n";

}

TEST_CASE("the bash script matches the golden projection byte-for-byte", "[completion]")
{
    REQUIRE(generate_completion(shell::bash, fixture(), "myapp") == expected_bash);
}

TEST_CASE("the zsh script matches the golden projection byte-for-byte", "[completion]")
{
    REQUIRE(generate_completion(shell::zsh, fixture(), "myapp") == expected_zsh);
}

TEST_CASE("completion renders flags under the host-chosen delimiter", "[completion][delimiter]")
{
    const auto delim = nucleus::cli_delimiter::parse("__").value();
    const std::string bash = generate_completion(shell::bash, fixture(), "myapp", delim);
    REQUIRE(bash.find("--logging__level") != std::string::npos);
    REQUIRE(bash.find("--logging-level") == std::string::npos);
}

TEST_CASE("anchored completion offers only the anchor's subtree, relative", "[completion][anchor]")
{
    const std::string bash = generate_completion(shell::bash, fixture(), "myapp", {},
                                                 path_of("logging"));
    // Under the anchor: the leaf completes by its relative flag, values intact.
    REQUIRE(bash.find("'--level'") != std::string::npos);
    REQUIRE(bash.find("debug info warn error") != std::string::npos);
    // Outside the anchor (and the anchor itself): not addressable, not offered.
    REQUIRE(bash.find("--plexus") == std::string::npos);
    REQUIRE(bash.find("--logging") == std::string::npos);
}

TEST_CASE("zsh uses its own _arguments model, not reused bash quoting", "[completion]")
{
    const std::string zsh = generate_completion(shell::zsh, fixture(), "myapp");
    REQUIRE(zsh.find("#compdef myapp") != std::string::npos);
    REQUIRE(zsh.find("_arguments -s") != std::string::npos);
    // The bash-only machinery must NOT appear in the zsh dialect.
    REQUIRE(zsh.find("compgen") == std::string::npos);
    REQUIRE(zsh.find("COMPREPLY") == std::string::npos);
}

TEST_CASE("adding a flag changes the generated completion", "[completion][drift]")
{
    schema_registry reg = fixture();
    const std::string before = generate_completion(shell::bash, reg, "myapp");

    REQUIRE(reg.attach(nucleus::element("verbose", anchor::root())));
    const std::string after = generate_completion(shell::bash, reg, "myapp");

    REQUIRE(after != before);
    REQUIRE(before.find("--verbose") == std::string::npos);
    REQUIRE(after.find("--verbose") != std::string::npos);
}

TEST_CASE("adding an enum value changes the generated completion", "[completion][drift]")
{
    schema_registry base;
    REQUIRE(base.attach(nucleus::element("logging", anchor::root())));
    REQUIRE(base.attach(nucleus::enum_element("level", anchor::keyspace(path_of("logging")),
                                      {"debug", "info"})));
    const std::string before = generate_completion(shell::bash, base, "myapp");
    const std::string before_zsh = generate_completion(shell::zsh, base, "myapp");

    schema_registry grown;
    REQUIRE(grown.attach(nucleus::element("logging", anchor::root())));
    REQUIRE(grown.attach(nucleus::enum_element("level", anchor::keyspace(path_of("logging")),
                                       {"debug", "info", "trace"})));
    const std::string after = generate_completion(shell::bash, grown, "myapp");
    const std::string after_zsh = generate_completion(shell::zsh, grown, "myapp");

    REQUIRE(after != before);
    REQUIRE(before.find("trace") == std::string::npos);
    REQUIRE(after.find("'debug info trace'") != std::string::npos);
    REQUIRE(after_zsh != before_zsh);
    REQUIRE(after_zsh.find("(debug info trace)") != std::string::npos);
}

TEST_CASE("a value containing a quote cannot break out of the bash literal",
          "[completion]")
{
    schema_registry reg;
    REQUIRE(reg.attach(nucleus::element("mode", anchor::root())));
    REQUIRE(reg.attach(nucleus::enum_element("kind", anchor::keyspace(path_of("mode")),
                                     {"a'b"})));
    const std::string bash = generate_completion(shell::bash, reg, "myapp");
    // The single quote is escaped via the close/escape/reopen idiom.
    REQUIRE(bash.find("'a'\\''b'") != std::string::npos);
}

// project() emits a wildcard entry for paths that cross a repeated container.
// The wildcard flag substitutes a '*' at the repeated-container position so the bash
// and zsh completion scripts can complete after any typed ordinal (e.g. --cluster-node-2-).
namespace {

schema_registry repeated_cluster_registry()
{
    schema_registry reg;
    REQUIRE(reg.attach(nucleus::element("cluster", anchor::root())));
    REQUIRE(reg.attach(nucleus::repeated_element("node", anchor::keyspace(path_of("cluster")))));
    REQUIRE(reg.attach(nucleus::element("endpoint", anchor::keyspace(path_of("cluster/node")))));
    REQUIRE(reg.attach(nucleus::element("port", anchor::keyspace(path_of("cluster/node/endpoint")))));
    return reg;
}

} // namespace

TEST_CASE("completion emits wildcard flag for path crossing a repeated container",
          "[completion][repeated_container]")
{
    const schema_registry reg = repeated_cluster_registry();
    const std::string bash = generate_completion(shell::bash, reg, "myapp");

    // Standard non-wildcard flag must still appear.
    REQUIRE(bash.find("--cluster-node-endpoint-port") != std::string::npos);

    // Wildcard flag: the repeated container segment followed by '*'.
    REQUIRE(bash.find("--cluster-node-*-endpoint-port") != std::string::npos);
}

TEST_CASE("completion wildcard entry appears in zsh script for repeated container",
          "[completion][repeated_container]")
{
    const schema_registry reg = repeated_cluster_registry();
    const std::string zsh = generate_completion(shell::zsh, reg, "myapp");

    REQUIRE(zsh.find("--cluster-node-endpoint-port") != std::string::npos);
    REQUIRE(zsh.find("--cluster-node-*-endpoint-port") != std::string::npos);
}

TEST_CASE("completion wildcard does not appear for non-repeated schema",
          "[completion][repeated_container]")
{
    const std::string bash = generate_completion(shell::bash, fixture(), "myapp");
    // fixture() has no repeated container -- no wildcard should be present.
    REQUIRE(bash.find("-*-") == std::string::npos);
}
